In [3]:
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
df=pd.read_csv('stroke.csv')
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [ ]:
imputer=SimpleImputer(strategy='mean',fill_value='unknown')
imputer.fit_transform(df[['bmi']])

array([[36.6       ],
       [28.89323691],
       [32.5       ],
       ...,
       [30.6       ],
       [25.6       ],
       [26.2       ]], shape=(5110, 1))

In [7]:
imputer=SimpleImputer(strategy='median',fill_value=0)
imputer.fit_transform(df[['bmi']])

array([[36.6],
       [28.1],
       [32.5],
       ...,
       [30.6],
       [25.6],
       [26.2]], shape=(5110, 1))

In [8]:
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
imputer=SimpleImputer(strategy='most_frequent',fill_value='unknown')
imputer.fit_transform(df[['Cabin']])

array([['B96 B98'],
       ['C85'],
       ['B96 B98'],
       ['C123'],
       ['B96 B98'],
       ['B96 B98'],
       ['E46'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['G6'],
       ['C103'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D56'],
       ['B96 B98'],
       ['A6'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C23 C25 C27'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B78'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D33'],
       ['B96 B98'],
       ['B30'],
       ['C52'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B28'],
       ['C83'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F33'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F G73'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C23 C25 C27'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E31'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A5'],
       ['D10 D12'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D26'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C110'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B58 B60'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E101'],
       ['D26'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F E69'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D47'],
       ['C123'],
       ['B96 B98'],
       ['B86'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F2'],
       ['B96 B98'],
       ['B96 B98'],
       ['C2'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E33'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B19'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A7'],
       ['B96 B98'],
       ['B96 B98'],
       ['C49'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F4'],
       ['B96 B98'],
       ['A32'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F2'],
       ['B4'],
       ['B80'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['G6'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A31'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D36'],
       ['B96 B98'],
       ['B96 B98'],
       ['D15'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C93'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C83'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C78'],
       ['B96 B98'],
       ['B96 B98'],
       ['D35'],
       ['B96 B98'],
       ['B96 B98'],
       ['G6'],
       ['C87'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B77'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E67'],
       ['B94'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C125'],
       ['C99'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C118'],
       ['B96 B98'],
       ['D7'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A19'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B49'],
       ['D'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C22 C26'],
       ['C106'],
       ['B58 B60'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E101'],
       ['B96 B98'],
       ['C22 C26'],
       ['B96 B98'],
       ['C65'],
       ['B96 B98'],
       ['E36'],
       ['C54'],
       ['B57 B59 B63 B66'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C7'],
       ['E34'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C32'],
       ['B96 B98'],
       ['D'],
       ['B96 B98'],
       ['B18'],
       ['B96 B98'],
       ['C124'],
       ['C91'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C2'],
       ['E40'],
       ['B96 B98'],
       ['T'],
       ['F2'],
       ['C23 C25 C27'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F33'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C128'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E33'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D37'],
       ['B96 B98'],
       ['B96 B98'],
       ['B35'],
       ['E50'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C82'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D36'],
       ['G6'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C78'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E10'],
       ['C52'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E44'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C23 C25 C27'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A34'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C104'],
       ['B96 B98'],
       ['B96 B98'],
       ['C111'],
       ['C92'],
       ['B96 B98'],
       ['B96 B98'],
       ['E38'],
       ['D21'],
       ['B96 B98'],
       ['B96 B98'],
       ['E12'],
       ['B96 B98'],
       ['E63'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D'],
       ['B96 B98'],
       ['A14'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B49'],
       ['B96 B98'],
       ['C93'],
       ['B37'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C30'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D20'],
       ['B96 B98'],
       ['C22 C26'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B79'],
       ['C65'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E25'],
       ['B96 B98'],
       ['B96 B98'],
       ['D46'],
       ['F33'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B73'],
       ['B96 B98'],
       ['B96 B98'],
       ['B18'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C95'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B38'],
       ['B96 B98'],
       ['B96 B98'],
       ['B39'],
       ['B22'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C86'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C70'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A16'],
       ['B96 B98'],
       ['E67'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C101'],
       ['E25'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E44'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C68'],
       ['B96 B98'],
       ['A10'],
       ['B96 B98'],
       ['E68'],
       ['B96 B98'],
       ['B41'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D20'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A20'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C125'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F4'],
       ['B96 B98'],
       ['B96 B98'],
       ['D19'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D50'],
       ['B96 B98'],
       ['D9'],
       ['B96 B98'],
       ['B96 B98'],
       ['A23'],
       ['B96 B98'],
       ['B50'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B35'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D33'],
       ['B96 B98'],
       ['A26'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D48'],
       ['B96 B98'],
       ['B96 B98'],
       ['E58'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C126'],
       ['B96 B98'],
       ['B71'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B51 B53 B55'],
       ['B96 B98'],
       ['D49'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B5'],
       ['B20'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C68'],
       ['F G63'],
       ['C62 C64'],
       ['E24'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E24'],
       ['B96 B98'],
       ['B96 B98'],
       ['C90'],
       ['C124'],
       ['C126'],
       ['B96 B98'],
       ['B96 B98'],
       ['F G73'],
       ['C45'],
       ['E101'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E8'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B5'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B101'],
       ['B96 B98'],
       ['B96 B98'],
       ['D45'],
       ['C46'],
       ['B57 B59 B63 B66'],
       ['B96 B98'],
       ['B96 B98'],
       ['B22'],
       ['B96 B98'],
       ['B96 B98'],
       ['D30'],
       ['B96 B98'],
       ['B96 B98'],
       ['E121'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B77'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D11'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E77'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['F38'],
       ['B96 B98'],
       ['B96 B98'],
       ['B3'],
       ['B96 B98'],
       ['B20'],
       ['D6'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B82 B84'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D17'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A36'],
       ['B96 B98'],
       ['B96 B98'],
       ['E8'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B102'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B69'],
       ['B96 B98'],
       ['B96 B98'],
       ['E121'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B28'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E49'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C47'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C92'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D28'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['E17'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D17'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['A24'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D35'],
       ['B51 B53 B55'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C50'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B42'],
       ['B96 B98'],
       ['C148'],
       ['B96 B98']], dtype=object)

In [13]:
imputer=SimpleImputer(strategy='constant',fill_value=0)
imputer.fit_transform(df[['Cabin']])

array([[0],
       ['C85'],
       [0],
       ['C123'],
       [0],
       [0],
       ['E46'],
       [0],
       [0],
       [0],
       ['G6'],
       ['C103'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D56'],
       [0],
       ['A6'],
       [0],
       [0],
       [0],
       ['C23 C25 C27'],
       [0],
       [0],
       [0],
       ['B78'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D33'],
       [0],
       ['B30'],
       ['C52'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B28'],
       ['C83'],
       [0],
       [0],
       [0],
       ['F33'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['F G73'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C23 C25 C27'],
       [0],
       [0],
       [0],
       ['E31'],
       [0],
       [0],
       [0],
       ['A5'],
       ['D10 D12'],
       [0],
       [0],
       [0],
       [0],
       ['D26'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C110'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B58 B60'],
       [0],
       [0],
       [0],
       [0],
       ['E101'],
       ['D26'],
       [0],
       [0],
       [0],
       ['F E69'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D47'],
       ['C123'],
       [0],
       ['B86'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['F2'],
       [0],
       [0],
       ['C2'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E33'],
       [0],
       [0],
       [0],
       ['B19'],
       [0],
       [0],
       [0],
       ['A7'],
       [0],
       [0],
       ['C49'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['F4'],
       [0],
       ['A32'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['F2'],
       ['B4'],
       ['B80'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['G6'],
       [0],
       [0],
       [0],
       ['A31'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D36'],
       [0],
       [0],
       ['D15'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C93'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C83'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C78'],
       [0],
       [0],
       ['D35'],
       [0],
       [0],
       ['G6'],
       ['C87'],
       [0],
       [0],
       [0],
       [0],
       ['B77'],
       [0],
       [0],
       [0],
       [0],
       ['E67'],
       ['B94'],
       [0],
       [0],
       [0],
       [0],
       ['C125'],
       ['C99'],
       [0],
       [0],
       [0],
       ['C118'],
       [0],
       ['D7'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['A19'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B49'],
       ['D'],
       [0],
       [0],
       [0],
       [0],
       ['C22 C26'],
       ['C106'],
       ['B58 B60'],
       [0],
       [0],
       [0],
       ['E101'],
       [0],
       ['C22 C26'],
       [0],
       ['C65'],
       [0],
       ['E36'],
       ['C54'],
       ['B57 B59 B63 B66'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C7'],
       ['E34'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C32'],
       [0],
       ['D'],
       [0],
       ['B18'],
       [0],
       ['C124'],
       ['C91'],
       [0],
       [0],
       [0],
       ['C2'],
       ['E40'],
       [0],
       ['T'],
       ['F2'],
       ['C23 C25 C27'],
       [0],
       [0],
       [0],
       ['F33'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C128'],
       [0],
       [0],
       [0],
       [0],
       ['E33'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D37'],
       [0],
       [0],
       ['B35'],
       ['E50'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C82'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B96 B98'],
       [0],
       [0],
       ['D36'],
       ['G6'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C78'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E10'],
       ['C52'],
       [0],
       [0],
       [0],
       ['E44'],
       ['B96 B98'],
       [0],
       [0],
       ['C23 C25 C27'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['A34'],
       [0],
       [0],
       [0],
       ['C104'],
       [0],
       [0],
       ['C111'],
       ['C92'],
       [0],
       [0],
       ['E38'],
       ['D21'],
       [0],
       [0],
       ['E12'],
       [0],
       ['E63'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D'],
       [0],
       ['A14'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B49'],
       [0],
       ['C93'],
       ['B37'],
       [0],
       [0],
       [0],
       [0],
       ['C30'],
       [0],
       [0],
       [0],
       ['D20'],
       [0],
       ['C22 C26'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B79'],
       ['C65'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E25'],
       [0],
       [0],
       ['D46'],
       ['F33'],
       [0],
       [0],
       [0],
       ['B73'],
       [0],
       [0],
       ['B18'],
       [0],
       [0],
       [0],
       ['C95'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B38'],
       [0],
       [0],
       ['B39'],
       ['B22'],
       [0],
       [0],
       [0],
       ['C86'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C70'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['A16'],
       [0],
       ['E67'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C101'],
       ['E25'],
       [0],
       [0],
       [0],
       [0],
       ['E44'],
       [0],
       [0],
       [0],
       ['C68'],
       [0],
       ['A10'],
       [0],
       ['E68'],
       [0],
       ['B41'],
       [0],
       [0],
       [0],
       ['D20'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['A20'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C125'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['F4'],
       [0],
       [0],
       ['D19'],
       [0],
       [0],
       [0],
       ['D50'],
       [0],
       ['D9'],
       [0],
       [0],
       ['A23'],
       [0],
       ['B50'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B35'],
       [0],
       [0],
       [0],
       ['D33'],
       [0],
       ['A26'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D48'],
       [0],
       [0],
       ['E58'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C126'],
       [0],
       ['B71'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B51 B53 B55'],
       [0],
       ['D49'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B5'],
       ['B20'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C68'],
       ['F G63'],
       ['C62 C64'],
       ['E24'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E24'],
       [0],
       [0],
       ['C90'],
       ['C124'],
       ['C126'],
       [0],
       [0],
       ['F G73'],
       ['C45'],
       ['E101'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E8'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B5'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B101'],
       [0],
       [0],
       ['D45'],
       ['C46'],
       ['B57 B59 B63 B66'],
       [0],
       [0],
       ['B22'],
       [0],
       [0],
       ['D30'],
       [0],
       [0],
       ['E121'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B77'],
       [0],
       [0],
       [0],
       ['B96 B98'],
       [0],
       ['D11'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E77'],
       [0],
       [0],
       [0],
       ['F38'],
       [0],
       [0],
       ['B3'],
       [0],
       ['B20'],
       ['D6'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B82 B84'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['D17'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B96 B98'],
       [0],
       [0],
       [0],
       ['A36'],
       [0],
       [0],
       ['E8'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B102'],
       [0],
       [0],
       [0],
       [0],
       ['B69'],
       [0],
       [0],
       ['E121'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B28'],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['E49'],
       [0],
       [0],
       [0],
       ['C47'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C92'],
       [0],
       [0],
       [0],
       ['D28'],
       [0],
       [0],
       [0],
       ['E17'],
       [0],
       [0],
       [0],
       [0],
       ['D17'],
       [0],
       [0],
       [0],
       [0],
       ['A24'],
       [0],
       [0],
       [0],
       ['D35'],
       ['B51 B53 B55'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['C50'],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       ['B42'],
       [0],
       ['C148'],
       [0]], dtype=object)