In [32]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [33]:
encodes=LabelEncoder()

In [34]:
encodes.fit_transform(Xtrain[column])
encodes.fit_transform(Xtrain[column])
encoder.transform(Xtest[colname])
encoder.transform(Xtest[colname])

NameError: name 'Xtrain' is not defined

In [ ]:
encodes=OneHotEncoder(handle_unknown='ignore'|'error'(default),sparse_output=True|False (default))

<>:1: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'bool' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'bool' object is not callable; perhaps you missed a comma?
C:\Users\DELL\AppData\Local\Temp\ipykernel_19580\3916811126.py:1: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  encodes=OneHotEncoder(handle_unknown='ignore'|'error'(default),sparse_output=True|False (default))
C:\Users\DELL\AppData\Local\Temp\ipykernel_19580\3916811126.py:1: SyntaxWarning: 'bool' object is not callable; perhaps you missed a comma?
  encodes=OneHotEncoder(handle_unknown='ignore'|'error'(default),sparse_output=True|False (default))

NameError: name 'default' is not defined

In [ ]:
encodes.fit_transform(Xtrain[column])
encodes.fit_transform(Xtrain[column])
encoder.transform(Xtest[colname])
encoder.transform(Xtest[colname])

NameError: name 'Xtrain' is not defined

In [ ]:
encoder=OrdinalEncoder()

In [ ]:
encoder=OrdinalEncoder(categories=[[col1,order],[col2,order]])
                                  [['A1','B1','A12','B2']
                                  ['High school','UG','PG','PhD']]

IndentationError: unexpected indent (1691897729.py, line 2)

In [ ]:
from Catergory_encoder import TargetEncoder
encoder=TargetEncoder()
encoder.fit_transform(Xtrain)

ModuleNotFoundError: No module named 'Catergory_encoder'

In [ ]:
import pandas as pd
import numpy as np
np.random.seed(42)

n_rows=1000
data={
    'color':np.random.choice(['red','blue','green'],n_rows),
    'size':np.random.choice(['small','medium','large'],n_rows),
    'material':np.random.choice(['plastic','metal','wood'],n_rows),
    'price':np.random.randint(10,500,n_rows)
}
df=pd.DataFrame(data)
df

     color    size material  price
0    green   large    metal    423
1      red   large  plastic    351
2    green   large  plastic    229
3    green   large     wood    400
4      red   small  plastic    172
..     ...     ...      ...    ...
995   blue   small     wood    286
996   blue   large  plastic    473
997  green  medium  plastic    213
998  green   large    metal    203
999    red   large    metal    178

[1000 rows x 4 columns]

In [ ]:
pip install category_encoders

Collecting category_encoders
  Using cached category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from category_encoders) (2.4.2)
Requirement already satisfied: pandas>=1.0.5 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from category_encoders) (3.0.1)
Collecting patsy>=0.5.1 (from category_encoders)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from category_encoders) (1.17.1)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Using cached statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Using cached category_encoders-2.9.0-py3-none-any.whl (85 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 317.3 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/9.6 MB 317.3 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/9.6 MB 431.7 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.6 MB 431.7 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.6 MB 467.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 467.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 467.8 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 439.6 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 439.6 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 439.6 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 439.6 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 439.6 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.6 MB 397.2 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.6 MB 397.2 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.6 MB 415.9 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.6 MB 415.9 kB/s eta 0:00:19
   ------- -------------------------------- 1.8/9.6 MB 415.9 kB/s eta 0:00:19
   -------- ------------------------------- 2.1/9.6 MB 423.9 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.6 MB 423.9 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.6 MB 423.9 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.6 MB 428.7 kB/s eta 0:00:17
   --------- ------------------------------ 2.4/9.6 MB 428.7 kB/s eta 0:00:17
   --------- ------------------------------ 2.4/9.6 MB 428.7 kB/s eta 0:00:17
   ---------- ----------------------------- 2.6/9.6 MB 426.6 kB/s eta 0:00:17
   ---------- ----------------------------- 2.6/9.6 MB 426.6 kB/s eta 0:00:17
   ---------- ----------------------------- 2.6/9.6 MB 426.6 kB/s eta 0:00:17
   ------------ --------------------------- 2.9/9.6 MB 423.6 kB/s eta 0:00:16
   ------------ --------------------------- 2.9/9.6 MB 423.6 kB/s eta 0:00:16
   ------------ --------------------------- 2.9/9.6 MB 423.6 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 420.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 420.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 420.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 420.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 420.7 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   -------------- ------------------------- 3.4/9.6 MB 390.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.6 MB 351.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.6 MB 302.3 kB/s eta 0:00:19
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ----------------- ---------------------- 4.2/9.6 MB 264.6 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------ --------------------- 4.5/9.6 MB 247.2 kB/s eta 0:00:21
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   ------------------- -------------------- 4.7/9.6 MB 209.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   -------------------- ------------------- 5.0/9.6 MB 192.3 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   --------------------- ------------------ 5.2/9.6 MB 189.3 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.6 MB 185.4 kB/s eta 0:00:23
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------ --------------- 5.8/9.6 MB 183.9 kB/s eta 0:00:21
   ------------------------- -------------- 6.0/9.6 MB 175.3 kB/s eta 0:00:21
   ------------------------- -------------- 6.0/9.6 MB 175.3 kB/s eta 0:00:21
   ------------------------- -------------- 6.0/9.6 MB 175.3 kB/s eta 0:00:21
   ------------------------- -------------- 6.0/9.6 MB 175.3 kB/s eta 0:00:21
   -------------------------- ------------- 6.3/9.6 MB 168.0 kB/s eta 0:00:20
   -------------------------- ------------- 6.3/9.6 MB 168.0 kB/s eta 0:00:20
   -------------------------- ------------- 6.3/9.6 MB 168.0 kB/s eta 0:00:20
   --------------------------- ------------ 6.6/9.6 MB 169.2 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.6 MB 169.2 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.6 MB 169.2 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.6 MB 169.2 kB/s eta 0:00:18
   --------------------------- ------------ 6.6/9.6 MB 169.2 kB/s eta 0:00:18
   ---------------------------- ----------- 6.8/9.6 MB 166.7 kB/s eta 0:00:17
   ---------------------------- ----------- 6.8/9.6 MB 166.7 kB/s eta 0:00:17
   ---------------------------- ----------- 6.8/9.6 MB 166.7 kB/s eta 0:00:17
   ---------------------------- ----------- 6.8/9.6 MB 166.7 kB/s eta 0:00:17
   ----------------------------- ---------- 7.1/9.6 MB 158.8 kB/s eta 0:00:16
   ----------------------------- ---------- 7.1/9.6 MB 158.8 kB/s eta 0:00:16
   ----------------------------- ---------- 7.1/9.6 MB 158.8 kB/s eta 0:00:16
   ----------------------------- ---------- 7.1/9.6 MB 158.8 kB/s eta 0:00:16
   ----------------------------- ---------- 7.1/9.6 MB 158.8 kB/s eta 0:00:16
   ------------------------------ --------- 7.3/9.6 MB 151.7 kB/s eta 0:00:15
   ------------------------------ --------- 7.3/9.6 MB 151.7 kB/s eta 0:00:15
   ------------------------------ --------- 7.3/9.6 MB 151.7 kB/s eta 0:00:15
   ------------------------------- -------- 7.6/9.6 MB 151.4 kB/s eta 0:00:14
   ------------------------------- -------- 7.6/9.6 MB 151.4 kB/s eta 0:00:14
   -------------------------------- ------- 7.9/9.6 MB 158.1 kB/s eta 0:00:11
   --------------------------------- ------ 8.1/9.6 MB 163.1 kB/s eta 0:00:09
   --------------------------------- ------ 8.1/9.6 MB 163.1 kB/s eta 0:00:09
   ---------------------------------- ----- 8.4/9.6 MB 169.7 kB/s eta 0:00:08
   ---------------------------------- ----- 8.4/9.6 MB 169.7 kB/s eta 0:00:08
   ------------------------------------ --- 8.7/9.6 MB 176.3 kB/s eta 0:00:06
   ------------------------------------ --- 8.7/9.6 MB 176.3 kB/s eta 0:00:06
   ------------------------------------- -- 8.9/9.6 MB 184.5 kB/s eta 0:00:04
   -------------------------------------- - 9.2/9.6 MB 192.2 kB/s eta 0:00:03
   ---------------------------------------  9.4/9.6 MB 199.3 kB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 202.6 kB/s  0:00:39
Installing collected packages: patsy, statsmodels, category_encoders

   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/category-encoders/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/category-encoders/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/category-encoders/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/category-encoders/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/patsy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/patsy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/patsy/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/statsmodels/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/statsmodels/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/statsmodels/

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
import pandas as pd
import numpy as np
np.random.seed(42)

n_rows=1000
data={
    'color':np.random.choice(['red','blue','green'],n_rows),
    'size':np.random.choice(['small','medium','large'],n_rows),
    'material':np.random.choice(['plastic','metal','wood'],n_rows),
    'price':np.random.randint(10,500,n_rows)
}
df=pd.DataFrame(data)
df

     color    size material  price
0    green   large    metal    423
1      red   large  plastic    351
2    green   large  plastic    229
3    green   large     wood    400
4      red   small  plastic    172
..     ...     ...      ...    ...
995   blue   small     wood    286
996   blue   large  plastic    473
997  green  medium  plastic    213
998  green   large    metal    203
999    red   large    metal    178

[1000 rows x 4 columns]

In [ ]:
X=df.drop(columns='price')
y=df.price
xtrain,xtest,ytrain,ytest=train_test_split(X,y,train_size=0.8,random_state=42)

In [ ]:
#Label encoder
label_encoder=LabelEncoder()
updated_xtrain=label_encoder.fit_transform(xtrain)
#value error

ValueError: y should be a 1d array, got an array of shape (800, 3) instead.

In [35]:
label_encoder.fit_transform(xtrain)

ValueError: y should be a 1d array, got an array of shape (800, 3) instead.

In [ ]:
#new input
new_input=['red','red','white']
label_encoder.transform(new_input)

NotFittedError: This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
#OneHotEncoder
# encoder=OneHotEncoder()
encoder=OneHotEncoder(sparse_output=False)
values=encoder.fit_transform(xtrain)
#toaaray()
# values.toarray()
# values=values.toarray()
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 9))

In [39]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

In [43]:
pd.DataFrame(values,columns=columns)

NameError: name 'columns' is not defined

In [53]:
encoder.transform(xtest)

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(200, 9))

In [60]:
# new_input=[['red','large'],['blue','small']]  #ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
# encoder.transform(new_input)
# new_input=[['red1','large','plastic'],['blue','small','wood']]   #ValueError: Found unknown categories ['red1'] in column 0 during transform
new_input=[['red','large','plastic'],['blue','small','wood']]
encoder.transform(new_input)

c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [65]:
encoder=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
values=encoder.fit_transform(xtrain)
updated_xtrain=encoder.fit_transform(xtrain)
new_input=[['red1','large','plastic'],['blue','small','wood']]
encoder.transform(new_input)
#it assign the value 0 to the unknown category red1 and does not throw an error. This is useful when you have new categories in the test set that were not present in the training set.

c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [62]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)